sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: grPMD7d9RB+sHzxjqWh2S2E3xTT7XCRw6GXEZvI5pyi8Em/pE9HkbyZxKrBGB39S3NMTNv2b/hfDX98PdMPvybyrv/W1xqx/C6qhltitM1+TbffkfT8FZCml+5cCQbcH2kTCN4wBH17Ya3uoUp4Z+tkJwFUVurXDgMWEoZOlqbowwWbfD3WiqcXNfY/pIqSox7zWzzTOIurcmI5fOLhNiJu/Au8SSHUIwjGNpJu4ADt4o8XeHANLcI5EFXUNOih1AOdSBN0HcWegGHIwzpUzowBwTycnNTgZ4Q12q8p3ofI6l+XCVMfhpxzu+6jcOXX1eajyO9pRt+4FMoOw2ZzLjHLZxzC9207YogbOLOlQm2uwdZ4pOOp51hlNEXQ6un7H9pJaPQiCJHQyYmCa/iIldP2oXELodIA030/bhdn+HmilK51c9iiPigtc4U+tyh2QOUCUxlIUJfIZyqAZnAjooGcALiRY4sB3EpLl0+mNKcmDIPHMs+GbUqA2lJGdTyFU3LOAKYIC6GbGdR75rqo+ErWFRtPSaMHUI3KCB9EN6TRI8x0TQ/vaLniBOwrtbzU3zxoV0hsnHbUzH+RsA7B4Z38mifNtzqlxxIdR1aKhUJpdN4/cRqfhx+pmZqoVQS4PXmwtM5fYMiVZNj3tPPQkHc0MytDpYCO4QNh05Qp/bZo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Seven-Poor-Travellers_1392
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy